#!/usr/bin/env bash
if sudo -v; then 
    echo "Proceeding..."
    # Part 1
    sudo dnf update -y
    sudo dnf groupinstall -y 'Development Tools'
    sudo dnf install -y procps-ng curl file git lsd
    
    # Part 2
    if [ ! -d /home/linuxbrew ]; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install fzf micro fd oh-my-posh topgrade ripgrep fish
        sudo ln -s $(which fish) /bin/fish
        sudo ln -s $(which fzf) /bin/fzf
        sudo ln -s $(which fd) /bin/fd
        sudo ln -s $(which micro) /bin/micro
        sudo ln -s $(which rg) /bin/rg
    fi
    
    # Part 3
    if [ ! -d /nix/ ]; then
        sh <(curl -L https://nixos.org/nix/install) --daemon
    fi
    
    # Part 4
    echo "/bin/fish" | sudo tee -a /etc/shells
    echo "/usr/bin/fish" | sudo tee -a /etc/shells
    sudo chsh user --shell /bin/fish
    echo -e "Please manually execute the following as the script cannot do it:\nnix-env -i wslu"
    exec bash
else
    echo "You do not have sudo privileges."
    exit 1
fi

