#!/usr/bin/env fish
# Test if fish is installed
bash -c 'if ! command -V fish > /dev/null 2>&1; then; echo "Please make sure to install fish before executing this script!"; exit; fi'

# Part 1
curl -sL 'https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish' | source && fisher install jorgebucaran/fisher

# Part 2
fisher install jorgebucaran/replay.fish
fisher install catppuccin/fish
fisher install kidonng/nix.fish 
fisher install kidonng/nix-completions.fish

# Part 3
curl 'https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install' | fish
